name: VMManager CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend
  
jobs:
  lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Go Vet
        run: go vet ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 5m


  security-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner for ./backend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './'
          format: 'sarif'
          output: 'trivy-backend-fs.sarif'
          severity: 'HIGH,CRITICAL'
          scanners: 'vuln,secret,misconfig'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend-fs.sarif'

  test-and-build:
    needs: [security-scan]
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Start Redis
      uses: supercharge/redis-github-action@v1.8.0
      with:
        redis-version: 6

    - name: Run tests with Redis
      run: go test -v ./...
      
    - name: Build
      run: go build -v ./...